# Generated by Django 5.1.5 on 2025-01-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.IntegerField()),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('occupée', 'Occupée')], default='libre', max_length=20)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='api.parking')),
            ],
            options={
                'unique_together': {('parking', 'spot_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='place',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='place',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
